name: Publish Canary Image

# This workflow anticipates a repository_dispatch event from the following workflow:
# https://github.com/actions/actions-runner-controller/blob/master/.github/workflows/publish-canary.yaml
on: workflow_dispatch

# https://docs.github.com/en/rest/overview/permissions-required-for-github-apps
permissions:
  contents: read
  packages: write

env:
  TARGET_ORG: h0x0er
  TARGET_REPO: actions-runner-controller

jobs:
  canary-build:
    name: Build and Publish Canary Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: actions/actions-runner-controller
          path: arc/
          ref: master

      # Considered unstable builds
      # See Issue #285, PR #286, and PR #323 for more information
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./arc
          file: ./arc/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: VERSION=canary-master
          push: true
          tags: |
            ghcr.io/${{ env.TARGET_ORG }}/${{ env.TARGET_REPO }}:canary
          cache-from: type=gha,scope=arc-canary
          cache-to: type=gha,mode=max,scope=arc-canary
